# Generated by Django 5.0.9 on 2026-09-15 13:53

import apps.jobs.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("needs_review", "Needs Review"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("mode", models.CharField(max_length=32)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.jobs.models.output_upload_path,
                    ),
                ),
                ("output_width", models.PositiveIntegerField(blank=True, null=True)),
                ("output_height", models.PositiveIntegerField(blank=True, null=True)),
                ("output_checksum", models.CharField(blank=True, max_length=64)),
                ("qc_passed", models.BooleanField(blank=True, null=True)),
                ("qc_report", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.PositiveIntegerField(default=1)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="products.productimage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobStageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingest & Validate"),
                            ("enhance", "Quality Enhancement"),
                            ("ai_recreate", "AI Studio Recreation"),
                            ("remove_background", "Background Removal"),
                            ("compose_white", "Composite on White"),
                            ("square_center_pad", "Square / Center / Pad"),
                            ("export", "Export"),
                            ("qc", "Quality Control"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_logs",
                        to="jobs.processingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status"], name="jobs_proces_status_d38ef0_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["mode"], name="jobs_proces_mode_df51ff_idx"),
        ),
    ]
