# Generated by Django 5.0.9 on 2026-09-15 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PipelineSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("output_size_px", models.PositiveIntegerField(default=2000)),
                ("padding_percent", models.FloatField(default=8.0)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("WEBP", "WebP"), ("PNG", "PNG"), ("JPEG", "JPEG")],
                        default="WEBP",
                        max_length=10,
                    ),
                ),
                ("output_quality", models.PositiveIntegerField(default=90)),
                (
                    "qc_background_whiteness_tolerance",
                    models.FloatField(
                        default=6.0,
                        help_text="Max allowed mean deviation from #FFFFFF in corner samples (0-255 scale).",
                    ),
                ),
                (
                    "qc_centering_tolerance_percent",
                    models.FloatField(
                        default=2.5,
                        help_text="Max allowed asymmetry between opposite padding edges, as % of canvas size.",
                    ),
                ),
                ("qc_min_product_coverage_percent", models.FloatField(default=15.0)),
                ("qc_max_product_coverage_percent", models.FloatField(default=95.0)),
                (
                    "qc_identity_similarity_threshold",
                    models.FloatField(
                        default=0.8,
                        help_text="Min similarity score (0-1) between source and AI-recreated product region.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Settings",
                "verbose_name_plural": "Pipeline Settings",
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional product category scope, e.g. 'footwear'.",
                        max_length=100,
                    ),
                ),
                (
                    "template_text",
                    models.TextField(
                        default="A professional studio product photograph of the exact same item shown in the reference image, front-facing, centered, on a seamless pure white background, soft even studio lighting, no shadows other than a subtle contact shadow, sharp focus, high detail. Preserve the product's exact shape, proportions, color, material, texture, logos, and any printed text with complete accuracy. Do not invent, add, remove, or alter any product features."
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="StorageSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("s3", "AWS S3"),
                            ("r2", "Cloudflare R2"),
                            ("local", "Local filesystem (dev only)"),
                        ],
                        default="s3",
                        max_length=20,
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(default="pixelforge-media", max_length=255),
                ),
                ("region", models.CharField(default="auto", max_length=100)),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        help_text="Required for R2 / non-AWS S3-compatible endpoints.",
                    ),
                ),
                ("path_prefix", models.CharField(default="pixelforge", max_length=100)),
                ("signed_url_ttl_seconds", models.PositiveIntegerField(default=3600)),
            ],
            options={
                "verbose_name": "Storage Settings",
                "verbose_name_plural": "Storage Settings",
            },
        ),
    ]
